### ISSUE TITLE
Buradaki listeler çok daha güzel uygulanabilir.

### ISSUE THREAD

**Issue by E-MRE** [EdebaliErman/fal_bakalim#2]
https://github.com/EdebaliErman/fal_bakalim/blob/a7f20cddc9f70bc2d63d38313705ae8088663927/lib/string_items.dart#L1

Engin hocanın videolarından hatırlamalısın, yerinde olsam abstract class oluşturur içerisine bir kaç metot eklerdim.

`List<String> getAll();
String getRandom();
String getByIndex(int index);`

şeklinde.

sonra bu abstract class'tan sınıflar türetirdim.  dosyadaki her bir liste aslında sınıf yapılabilir. love, life, work vb.

bu sınıfların içinde onlara has fal listesi olur ve implement ettiğim metotları da bu listeyi kullanarak içini doldururum.

**Comment by EdebaliErman** [comment]
Teşekkürler
